
###==Users Controller==###

###
http://localhost:8000/api/v1/users

###
GET http://localhost:8000/api/v1/users/1

###
POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
  "username": "moo",
  "name": "Cow",
  "avatar": "https://bulma.io/assets/images/placeholders/128x128.png",
  "is_administrator": false
}

###
PATCH http://localhost:8000/api/v1/users/1
Content-Type: application/json

{
  "name": "Orange",
  "username": "jason",
  "avatar": "https://bulma.io/assets/images/placeholders/128x128.png",
  "is_administrator": false
}
###
DELETE http://localhost:8000/api/v1/users/5
Content-Type: application/json

{
  "name": "Sokka",
  "username": "sokka",
  "avatar": "https://bulma.io/assets/images/placeholders/128x128.png",
  "is_administrator": false
}

########--Activity Controller--########

###
http://localhost:8000/api/v1/activities

###
GET http://localhost:8000/api/v1/activities/2

###
POST http://localhost:8000/api/v1/activities
Content-Type: application/json

{
    "user_id": 1,
    "exercise_id": 1,
    "content": "Hello",
    "created_at": "2023-10-01T00:00:00Z"
}

###
PATCH http://localhost:8000/api/v1/activities/1
Content-Type: application/json

{
    "user_id": 2,
    "exercise_id": 7,
    "content": "Hello",
    "created_at": "2023-10-01T00:00:00Z"
}

###
DELETE http://localhost:8000/api/v1/activities/4

###
GET http://localhost:8000/api/v1/activities/user/janedoe



####--ExerciseType Controller--####

###
http://localhost:8000/api/v1/exerciseTypes

###
GET http://localhost:8000/api/v1/exerciseTypes/10

###
POST http://localhost:8000/api/v1/exerciseTypes
Content-Type: application/json

{
    "exercise": "jumping jacks"
}

###
PATCH http://localhost:8000/api/v1/exerciseTypes/1
Content-Type: application/json

{
    "exercise": "Running"
}

###
DELETE http://localhost:8000/api/v1/exerciseTypes/10
